backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Page d'accueil"
        name: "index"
        fields:
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text},{label: Lien, name: lien, widget: string}]}]}
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Main, name: main, widget: object, fields: [{label: Image1, name: image1, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Body, name: body, widget: markdown}, {label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Body, name: body, widget: markdown}, {label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Contact, name: contact, widget: text, output_code_only: 'true'}
      - file: "src/pages/presentation/index.md"
        label: "Presentation"
        name: "presentation"
        fields:
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "presentation-page"}
          - {label: "Main1", name: main1, widget: object, fields: [{label: Title, name: title, widget: text}, {label: Description1, name: description1, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: text, widget: text}]}, {label: Description2, name: description2, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: text, widget: text}]}, {label: Description3, name: description3, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: text, widget: text}]}, {label: Description4, name: description4, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: text, widget: text}]}]}
          - {label: "Main2", name: main2, widget: object, fields: [{label: Title, name: title, widget: text}, {label: Description1, name: description1, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: text, widget: text}]}, {label: Description2, name: description2, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: text, widget: text}]}, {label: Description3, name: description3, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: text, widget: text}]}, {label: Description4, name: description4, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: text, widget: text}]}]}
      - file: "src/pages/about/index.md"
        label: "Honoraires"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Domaines d'intervention"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description1, name: description1, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: body, widget: markdown}]}, {label: Description2, name: description2, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: body, widget: markdown}]}, {label: Description3, name: description3, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: body, widget: markdown}]}, {label: Description4, name: description4, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: body, widget: markdown}]}, {label: Description5, name: description5, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: body, widget: markdown}]},{label: Description6, name: description6, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: body, widget: markdown}]}, {label: Description7, name: description7, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: body, widget: markdown}]}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/ventesJudiciaires/index.md"
              label: "Ventes judiciaires"
              name: "ventesJudiciaires"
              fields:
                - {label: "Template Key", name: "templateKey", widget: "hidden", default: "ventesJudiciaires-page"}
                - {label: Title, name: title, widget: string}
                - {label: Image, name: image, widget: image}
                - {label: Heading, name: heading, widget: string}
                - {label: Body, name: body, widget: markdown}
